package trabalho.ui;

import trabalho.Planilhas;
import trabalho.Relatorios;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import trabalho.exception.DadoAusenteException;
import trabalho.exception.DadoInconsistenteException;
import trabalho.exception.DisciplinaNaoEncontradaException;
import trabalho.exception.ElementoRepetidoException;
import trabalho.exception.ErroDeConsistenciaException;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jordão
 */
public class ModoNormalGUI extends javax.swing.JFrame {

    private final ModoLeitura ler;
    /**
     *
     */
    private boolean leuPC, leuPD, leuPAv, leuPA, leuPN;

    public ModoNormalGUI() {
        ler = new ModoLeitura();
        initComponents();
        jButtonEstadoNota.setBackground(new Color(255, 0, 0));
        jButtonEstadoAluno.setBackground(new Color(255, 0, 0));
        jButtonEstadoAvaliacoes.setBackground(new Color(255, 0, 0));
        jButtonEstadoDisciplina.setBackground(new Color(255, 0, 0));
        jButtonEstadoCurso.setBackground(new Color(255, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonPlanilhaCurso = new javax.swing.JButton();
        jButtonPlanilhaDisciplina = new javax.swing.JButton();
        jButtonPlanilhaAvaliacoes = new javax.swing.JButton();
        jButtonPlanilhaAluno = new javax.swing.JButton();
        jButtonPlanilhaNota = new javax.swing.JButton();
        jButtonEstadoCurso = new javax.swing.JButton();
        jButtonEstadoDisciplina = new javax.swing.JButton();
        jButtonEstadoAvaliacoes = new javax.swing.JButton();
        jButtonEstadoAluno = new javax.swing.JButton();
        jButtonEstadoNota = new javax.swing.JButton();
        jButtonSaida = new javax.swing.JButton();
        jButtonGeraRelatorio = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RelatorioAutomatizadoDeDisciplinasGUI");

        jPanel2.setBackground(new java.awt.Color(1, 1, 1));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));

        jButtonPlanilhaCurso.setText("Ler Planilha de Cursos");
        jButtonPlanilhaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlanilhaCursoActionPerformed(evt);
            }
        });

        jButtonPlanilhaDisciplina.setText("Ler Planilha de Disciplinas");
        jButtonPlanilhaDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlanilhaDisciplinaActionPerformed(evt);
            }
        });

        jButtonPlanilhaAvaliacoes.setText("Ler Planilha de Avaliacoes");
        jButtonPlanilhaAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlanilhaAvaliacoesActionPerformed(evt);
            }
        });

        jButtonPlanilhaAluno.setText("Ler Planilha de Alunos");
        jButtonPlanilhaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlanilhaAlunoActionPerformed(evt);
            }
        });

        jButtonPlanilhaNota.setText("Ler Planilha de Notas");
        jButtonPlanilhaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlanilhaNotaActionPerformed(evt);
            }
        });

        jButtonEstadoCurso.setText(" ");

        jButtonEstadoDisciplina.setText(" ");

        jButtonEstadoAvaliacoes.setText(" ");

        jButtonEstadoAluno.setText(" ");

        jButtonEstadoNota.setText(" ");

        jButtonSaida.setText("Sair");
        jButtonSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaidaActionPerformed(evt);
            }
        });

        jButtonGeraRelatorio.setText("Gerar Relatorio");
        jButtonGeraRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeraRelatorioActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButtonPlanilhaCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPlanilhaDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPlanilhaAvaliacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPlanilhaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPlanilhaNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonGeraRelatorio)
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEstadoCurso)
                            .addComponent(jButtonEstadoDisciplina)
                            .addComponent(jButtonEstadoAvaliacoes)
                            .addComponent(jButtonEstadoAluno)
                            .addComponent(jButtonEstadoNota)))
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlanilhaCurso)
                    .addComponent(jButtonEstadoCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlanilhaDisciplina)
                    .addComponent(jButtonEstadoDisciplina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlanilhaAvaliacoes)
                    .addComponent(jButtonEstadoAvaliacoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlanilhaAluno)
                    .addComponent(jButtonEstadoAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlanilhaNota)
                    .addComponent(jButtonEstadoNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGeraRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSaidaActionPerformed

    private void jButtonPlanilhaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlanilhaNotaActionPerformed
        ler.escolha.arqN = EscolheFile.escolhe();
        if (ler.escolha.arqN == null) {
            return;
        }

        jButtonEstadoNota.setBackground(new Color(0, 255, 51));
        leuPN = true;
    }//GEN-LAST:event_jButtonPlanilhaNotaActionPerformed

    private void jButtonPlanilhaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlanilhaAlunoActionPerformed
        ler.escolha.arqA = EscolheFile.escolhe();
        if (ler.escolha.arqA == null) {
            return;
        }
        ler.sA = ler.criaScroll(ler.tabelaA);
        jButtonEstadoAluno.setBackground(new Color(0, 255, 51));
        leuPA = true;
    }//GEN-LAST:event_jButtonPlanilhaAlunoActionPerformed

    private void jButtonPlanilhaAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlanilhaAvaliacoesActionPerformed
        ler.escolha.arqAv = EscolheFile.escolhe();
        if (ler.escolha.arqAv == null) {
            return;
        }

        jButtonEstadoAvaliacoes.setBackground(new Color(0, 255, 51));
        leuPAv = true;
    }//GEN-LAST:event_jButtonPlanilhaAvaliacoesActionPerformed

    private void jButtonPlanilhaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlanilhaCursoActionPerformed
        ler.escolha.arqC = EscolheFile.escolhe();
        if (ler.escolha.arqC == null) {
            return;
        }

        jButtonEstadoCurso.setBackground(new Color(0, 255, 51));
        leuPC = true;
    }//GEN-LAST:event_jButtonPlanilhaCursoActionPerformed

    private void jButtonPlanilhaDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlanilhaDisciplinaActionPerformed
        ler.escolha.arqD = EscolheFile.escolhe();
        if (ler.escolha.arqD == null) {
            return;
        }

        jButtonEstadoDisciplina.setBackground(new Color(0, 255, 51));
        leuPD = true;
    }//GEN-LAST:event_jButtonPlanilhaDisciplinaActionPerformed

    private void jButtonGeraRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeraRelatorioActionPerformed
        if (leuPD && leuPA && leuPAv && leuPC && leuPN) {
            try {
                Planilhas.LeituraCursoCSV(ler.C, ler.escolha.arqC);
                Planilhas.LeituraDisciplinaCSV(ler.D, ler.escolha.arqD);
                Planilhas.LeituraAlunoCSV(ler.D, ler.A, ler.C, ler.escolha.arqA);
                Planilhas.LeituraAvaliacaoCSV(ler.Av, ler.D, ler.escolha.arqAv);
                Planilhas.LeituraNotaCSV(ler.Av, ler.A, ler.escolha.arqN);
                Relatorios.geraRelatorioAavaliacoes(ler.D);
                Relatorios.geraRelatorioDisciplinas(ler.D);
                Relatorios.geraRelatorioEstatisticaPorDisciplina(ler.D);
                JOptionPane.showMessageDialog(null, "Relatório gerado com sucesso", "Relatório", JOptionPane.INFORMATION_MESSAGE);
                
            } catch ( IOException |DadoInconsistenteException | DadoAusenteException | ElementoRepetidoException | ErroDeConsistenciaException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage() + "\nVerifique suas planilhas e as leia novamente.", "Exceção", JOptionPane.ERROR_MESSAGE);
            }
            try {
                ler.escolha.arqC.close();
                ler.escolha.arqD.close();
                ler.escolha.arqA.close();
                ler.escolha.arqAv.close();
                ler.escolha.arqN.close();
                leuPD = leuPA = leuPAv = leuPC = leuPN = false;
                jButtonEstadoNota.setBackground(new Color(255, 0, 0));
                jButtonEstadoAluno.setBackground(new Color(255, 0, 0));
                jButtonEstadoAvaliacoes.setBackground(new Color(255, 0, 0));
                jButtonEstadoDisciplina.setBackground(new Color(255, 0, 0));
                jButtonEstadoCurso.setBackground(new Color(255, 0, 0));

            } catch (IOException ex) {
                Logger.getLogger(ModoNormalGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Leia todas as Planilhas", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonGeraRelatorioActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoNormalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoNormalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoNormalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoNormalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModoNormalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEstadoAluno;
    private javax.swing.JButton jButtonEstadoAvaliacoes;
    private javax.swing.JButton jButtonEstadoCurso;
    private javax.swing.JButton jButtonEstadoDisciplina;
    private javax.swing.JButton jButtonEstadoNota;
    private javax.swing.JButton jButtonGeraRelatorio;
    private javax.swing.JButton jButtonPlanilhaAluno;
    private javax.swing.JButton jButtonPlanilhaAvaliacoes;
    private javax.swing.JButton jButtonPlanilhaCurso;
    private javax.swing.JButton jButtonPlanilhaDisciplina;
    private javax.swing.JButton jButtonPlanilhaNota;
    private javax.swing.JButton jButtonSaida;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
