/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.ui;

import trabalho.Cursos;
import trabalho.Alunos;
import trabalho.Disciplinas;
import trabalho.Planilhas;
import trabalho.Avaliacoes;
import java.awt.*;
import java.io.*;
import java.util.logging.*;
import javax.swing.JOptionPane;
import trabalho.Relatorios;
import trabalho.exception.DadoAusenteException;
import trabalho.exception.DadoInconsistenteException;
import trabalho.exception.DisciplinaNaoEncontradaException;
import trabalho.exception.ElementoRepetidoException;
import trabalho.exception.ErroDeConsistenciaException;

/**
 *
 * @author jordao
 */
public class ReadOnlyGUI extends javax.swing.JFrame {

    private final ModoLeitura ler;
    /**
     * Creates new form ReadOnly
     */
    private boolean leuPC, leuPD, leuPAv, leuPA, leuPN;

    public ReadOnlyGUI() {
        ler = new ModoLeitura();
        initComponents();
        jButtonEstadoNota.setBackground(new Color(255, 0, 0));
        jButtonEstadoAluno.setBackground(new Color(255, 0, 0));
        jButtonEstadoAvaliacao.setBackground(new Color(255, 0, 0));
        jButtonEstadoDisciplina.setBackground(new Color(255, 0, 0));
        jButtonEstadoCurso.setBackground(new Color(255, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jButtonLerPlanilhaDisciplina = new javax.swing.JButton();
        jButtonLerPlanilhaCurso = new javax.swing.JButton();
        jButtonLerPlanilhaAvaliacao = new javax.swing.JButton();
        jButtonPlanilhaAluno = new javax.swing.JButton();
        jButtonLerPlanilhaNota = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonEstadoCurso = new javax.swing.JButton();
        jButtonEstadoDisciplina = new javax.swing.JButton();
        jButtonEstadoAluno = new javax.swing.JButton();
        jButtonEstadoAvaliacao = new javax.swing.JButton();
        jButtonEstadoNota = new javax.swing.JButton();
        jButtonSerializar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(1, 1, 1));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));

        jButtonLerPlanilhaDisciplina.setText("Ler Planilha de Disciplinas");
        jButtonLerPlanilhaDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerPlanilhaDisciplinaActionPerformed(evt);
            }
        });

        jButtonLerPlanilhaCurso.setText("Ler Planilha de Cursos");
        jButtonLerPlanilhaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerPlanilhaCursoActionPerformed(evt);
            }
        });

        jButtonLerPlanilhaAvaliacao.setText("Ler Planilha de Avaliacoes");
        jButtonLerPlanilhaAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerPlanilhaAvaliacaoActionPerformed(evt);
            }
        });

        jButtonPlanilhaAluno.setText("Ler Planilha de Alunos");
        jButtonPlanilhaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlanilhaAlunoActionPerformed(evt);
            }
        });

        jButtonLerPlanilhaNota.setText("Ler Planilha de Notas");
        jButtonLerPlanilhaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerPlanilhaNotaActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonEstadoCurso.setText(" ");

        jButtonEstadoDisciplina.setText(" ");

        jButtonEstadoAluno.setText(" ");

        jButtonEstadoAvaliacao.setText(" ");

        jButtonEstadoNota.setText(" ");

        jButtonSerializar.setText("Serializar");
        jButtonSerializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSerializarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonLerPlanilhaCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEstadoCurso))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonLerPlanilhaDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonEstadoDisciplina))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonLerPlanilhaAvaliacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonEstadoAvaliacao))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonPlanilhaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonEstadoAluno))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonLerPlanilhaNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonEstadoNota))
                    .addComponent(jButtonSerializar)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLerPlanilhaCurso)
                    .addComponent(jButtonEstadoCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLerPlanilhaDisciplina)
                    .addComponent(jButtonEstadoDisciplina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLerPlanilhaAvaliacao)
                    .addComponent(jButtonEstadoAvaliacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlanilhaAluno)
                    .addComponent(jButtonEstadoAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLerPlanilhaNota)
                    .addComponent(jButtonEstadoNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSerializar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLerPlanilhaDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerPlanilhaDisciplinaActionPerformed
        ler.escolha.arqD = EscolheFile.escolhe();
        if (ler.escolha.arqD == null) {
            return;
        }

        jButtonEstadoDisciplina.setBackground(new Color(0, 255, 51));
        leuPD = true;
    }//GEN-LAST:event_jButtonLerPlanilhaDisciplinaActionPerformed

    private void jButtonLerPlanilhaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerPlanilhaCursoActionPerformed
        ler.escolha.arqC = EscolheFile.escolhe();
        if (ler.escolha.arqC == null) {
            return;
        }
        jButtonEstadoCurso.setBackground(new Color(0, 255, 51));
        leuPA = true;
    }//GEN-LAST:event_jButtonLerPlanilhaCursoActionPerformed

    private void jButtonLerPlanilhaAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerPlanilhaAvaliacaoActionPerformed
        ler.escolha.arqAv = EscolheFile.escolhe();
        if (ler.escolha.arqAv == null) {
            return;
        }

        jButtonEstadoAvaliacao.setBackground(new Color(0, 255, 51));
        leuPAv = true;
    }//GEN-LAST:event_jButtonLerPlanilhaAvaliacaoActionPerformed

    private void jButtonPlanilhaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlanilhaAlunoActionPerformed
        ler.escolha.arqA = EscolheFile.escolhe();
        if (ler.escolha.arqA == null) {
            return;
        }

        jButtonEstadoAluno.setBackground(new Color(0, 255, 51));
        leuPA = true;
    }//GEN-LAST:event_jButtonPlanilhaAlunoActionPerformed

    private void jButtonLerPlanilhaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerPlanilhaNotaActionPerformed
        ler.escolha.arqN = EscolheFile.escolhe();
        if (ler.escolha.arqN == null) {
            return;
        }

        jButtonEstadoNota.setBackground(new Color(0, 255, 51));
        leuPN = true;
    }//GEN-LAST:event_jButtonLerPlanilhaNotaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSerializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSerializarActionPerformed
        if (leuPA && leuPN && leuPAv && leuPD && leuPN) {
            try {
                Planilhas.LeituraCursoCSV(ler.C, ler.escolha.arqC);
                Planilhas.LeituraDisciplinaCSV(ler.D, ler.escolha.arqD);
                Planilhas.LeituraAvaliacaoCSV(ler.Av, ler.D, ler.escolha.arqAv);
                Planilhas.LeituraAlunoCSV(ler.D, ler.A, ler.C, ler.escolha.arqA);
                Planilhas.LeituraNotaCSV(ler.Av, ler.A, ler.escolha.arqN);
                ObjectOutputStream out;
                out = new ObjectOutputStream(new FileOutputStream("semestre.dat"));
                Cursos c = ler.C;
                Avaliacoes ava = ler.Av;
                Alunos a = ler.A;
                Disciplinas d = ler.D;
                out.writeObject(c);
                out.writeObject(ava);
                out.writeObject(a);
                out.writeObject(d);
                out.close();
                JOptionPane.showMessageDialog(null,"Objetos serializados com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);
            } catch (ErroDeConsistenciaException | ElementoRepetidoException | DadoInconsistenteException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage() + "\nVerifique suas planilhas e as leia novamente.", "Exceção", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Exceção", JOptionPane.ERROR_MESSAGE);
            }
            try {
                ler.escolha.arqC.close();
                ler.escolha.arqD.close();
                ler.escolha.arqA.close();
                ler.escolha.arqAv.close();
                ler.escolha.arqN.close();
                leuPD = leuPA = leuPAv = leuPC = leuPN = false;
                jButtonEstadoNota.setBackground(new Color(255, 0, 0));
                jButtonEstadoAluno.setBackground(new Color(255, 0, 0));
                jButtonEstadoAvaliacao.setBackground(new Color(255, 0, 0));
                jButtonEstadoDisciplina.setBackground(new Color(255, 0, 0));
                jButtonEstadoCurso.setBackground(new Color(255, 0, 0));
               
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Exceção", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Leia todas as Planilhas", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadOnlyGUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonSerializarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadOnlyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadOnlyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadOnlyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadOnlyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadOnlyGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEstadoAluno;
    private javax.swing.JButton jButtonEstadoAvaliacao;
    private javax.swing.JButton jButtonEstadoCurso;
    private javax.swing.JButton jButtonEstadoDisciplina;
    private javax.swing.JButton jButtonEstadoNota;
    private javax.swing.JButton jButtonLerPlanilhaAvaliacao;
    private javax.swing.JButton jButtonLerPlanilhaCurso;
    private javax.swing.JButton jButtonLerPlanilhaDisciplina;
    private javax.swing.JButton jButtonLerPlanilhaNota;
    private javax.swing.JButton jButtonPlanilhaAluno;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSerializar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
