/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.ui;

import java.awt.Color;
import trabalho.Cursos;
import trabalho.Alunos;
import trabalho.Disciplinas;
import trabalho.Relatorios;
import trabalho.Avaliacoes;
import java.awt.event.*;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import trabalho.exception.DadoAusenteException;
import trabalho.exception.DadoInconsistenteException;
import trabalho.exception.DisciplinaNaoEncontradaException;

/**
 *
 * @author jordao
 */
public class WriteOnlyGUI extends javax.swing.JFrame {

    ModoLeitura ler;
    String[] relatorioDisciplinas;
    String relatorioEstatistica;
    String relatorioAvaliacao;
    /**
     * Creates new form WriteOnlyGUI
     */
    public boolean leuInfo, gerouRelatorio;

    public WriteOnlyGUI() {
        ler = new ModoLeitura();
        initComponents();
        jButtonEstadoRelatorio3.setBackground(new Color(255, 0, 0));
        jButtonEstadoRelatorio2.setBackground(new Color(255, 0, 0));
        jButtonEstadoRelatorio1.setBackground(new Color(255, 0, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jButtonSair = new javax.swing.JButton();
        jButtonEstadoRelatorio2 = new javax.swing.JButton();
        jButtonGeraRelatorio = new javax.swing.JButton();
        jButtonEstadoRelatorio3 = new javax.swing.JButton();
        jButtonEstadoRelatorio1 = new javax.swing.JButton();
        jButtonLerSerializados = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonRelatorioDisciplinas = new javax.swing.JButton();
        jButtonRelatorioEstatisticasDisciplina = new javax.swing.JButton();
        jButtonRelatorioAvaliacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(1, 1, 1));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonEstadoRelatorio2.setText(" ");

        jButtonGeraRelatorio.setText("Gerar Relatorio");
        jButtonGeraRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeraRelatorioActionPerformed(evt);
            }
        });

        jButtonEstadoRelatorio3.setText(" ");

        jButtonEstadoRelatorio1.setText(" ");

        jButtonLerSerializados.setText("Ler Dados Serializados");
        jButtonLerSerializados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerSerializadosActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonRelatorioDisciplinas.setText("1 -  Relatorio de Disciplinas");
        jButtonRelatorioDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioDisciplinasActionPerformed(evt);
            }
        });

        jButtonRelatorioEstatisticasDisciplina.setText("2 - Relatorio Estatistica");
        jButtonRelatorioEstatisticasDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioEstatisticasDisciplinaActionPerformed(evt);
            }
        });

        jButtonRelatorioAvaliacoes.setText("3 - Relatorio de Avaliações");
        jButtonRelatorioAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioAvaliacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGeraRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLerSerializados)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonRelatorioEstatisticasDisciplina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRelatorioDisciplinas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRelatorioAvaliacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEstadoRelatorio2)
                            .addComponent(jButtonEstadoRelatorio1)
                            .addComponent(jButtonEstadoRelatorio3))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonLerSerializados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEstadoRelatorio1)
                    .addComponent(jButtonRelatorioDisciplinas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEstadoRelatorio2)
                    .addComponent(jButtonRelatorioEstatisticasDisciplina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEstadoRelatorio3)
                    .addComponent(jButtonRelatorioAvaliacoes))
                .addGap(41, 41, 41)
                .addComponent(jButtonGeraRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonLerSerializadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerSerializadosActionPerformed
        if (!leuInfo) {
            ObjectInputStream in;
            try {
                in = new ObjectInputStream(new FileInputStream("semestre.dat"));
                ler.C = (Cursos) in.readObject();
                ler.Av = (Avaliacoes) in.readObject();
                ler.A = (Alunos) in.readObject();
                ler.D = (Disciplinas) in.readObject();
                JOptionPane.showMessageDialog(null, "Dados Serializados Lidos com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                leuInfo = true;
            } catch (IOException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Erro de I/O.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Informações já foram lidas.", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonLerSerializadosActionPerformed

    private void jButtonGeraRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeraRelatorioActionPerformed
        if (leuInfo) {
            if (gerouRelatorio) {
                JOptionPane.showMessageDialog(null, "Relatorio já foi gerado.", "Alerta", JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                relatorioAvaliacao = Relatorios.geraRelatorioAavaliacoes(ler.D);
                relatorioDisciplinas = Relatorios.geraRelatorioDisciplinas(ler.D);
                relatorioEstatistica = Relatorios.geraRelatorioEstatisticaPorDisciplina(ler.D);
                JOptionPane.showMessageDialog(null, "Relatorios Gerados com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                jButtonEstadoRelatorio3.setBackground(new Color(0, 255, 51));
                jButtonEstadoRelatorio2.setBackground(new Color(0, 255, 51));
                jButtonEstadoRelatorio1.setBackground(new Color(0, 255, 51));
            } catch (FileNotFoundException | DadoInconsistenteException | DadoAusenteException ex) {
            } catch (IOException ex) {
                Logger.getLogger(WriteOnlyGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            gerouRelatorio = true;
        } else {
            JOptionPane.showMessageDialog(null, "Dados Serializados inexistente, Use primeiro a opção ReadONly.", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGeraRelatorioActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonRelatorioDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioDisciplinasActionPerformed
        if (gerouRelatorio) {
            for (String s : relatorioDisciplinas) {
                LeRelatorio.geraTable(s);
            }
        }
    }//GEN-LAST:event_jButtonRelatorioDisciplinasActionPerformed

    private void jButtonRelatorioEstatisticasDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioEstatisticasDisciplinaActionPerformed
        if (gerouRelatorio) {
                LeRelatorio.geraTable(relatorioEstatistica);
        }
    }//GEN-LAST:event_jButtonRelatorioEstatisticasDisciplinaActionPerformed

    private void jButtonRelatorioAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioAvaliacoesActionPerformed
        if (gerouRelatorio) {
                LeRelatorio.geraTable(relatorioAvaliacao);
        }
    }//GEN-LAST:event_jButtonRelatorioAvaliacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WriteOnlyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WriteOnlyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WriteOnlyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WriteOnlyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WriteOnlyGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEstadoRelatorio1;
    private javax.swing.JButton jButtonEstadoRelatorio2;
    private javax.swing.JButton jButtonEstadoRelatorio3;
    private javax.swing.JButton jButtonGeraRelatorio;
    private javax.swing.JButton jButtonLerSerializados;
    private javax.swing.JButton jButtonRelatorioAvaliacoes;
    private javax.swing.JButton jButtonRelatorioDisciplinas;
    private javax.swing.JButton jButtonRelatorioEstatisticasDisciplina;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
