build:
	gcc *.c -c
	gcc *.o -o programa.out -lm
	rm *.o

executa_indice:
	./programa.out Texto.txt Palavras_Chave.txt Alfabeto.txt 1

executa_busca:
	./programa.out Texto.txt Palavras_Chave.txt Alfabeto.txt 2